version: "3.9"

services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: agrovista
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://usuario:password@db:5432/agrovista
    depends_on:
      - db
    ports:
      - "8000:8000"
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  pgdata:
